# Generated by Django 4.2.3 on 2023-07-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FICTION', 'Fiction'), ('FINANCE', 'Finance'), ('POLITICS', 'Politics'), ('ROMANCE', 'Romance')], default='Finance', max_length=11),
        ),
    ]
