# Generated by Django 4.2.3 on 2023-08-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=200)),
                ('description', models.CharField(choices=[('INTRESTING', 'Intresting'), ('SWEET', 'Sweet'), ('BORING', 'Boring')], default='intresting', max_length=15)),
            ],
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='date_returned',
            field=models.DateField(auto_now_add=True),
        ),
    ]
